pipeline {
    agent any

    stages {

        stage('Clone GitHub Repo') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/awsdevopsgp2020/git-jenkins-docker/webapp.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t webapp-local:latest .'
            }
        }

        stage('Stop Old Container') {
            steps {
                sh '''
                docker stop webapp || true
                docker rm webapp || true
                '''
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                docker run -d \
                --name webapp \
                -p 8081:80 \
                webapp-local:latest
                '''
            }
        }
    }
}
